### 파이썬 머신러닝 완벽가이드 p.88~
- 2장. 사이킷런
- 첫번째 머신러닝 만들어보기. 붓꽃 데이터 품종 예측하기

In [1]:
# 붓꽃 데이터 로드
from sklearn.datasets import load_iris
# 분류 알고리즘 로드
from sklearn.tree import DecisionTreeClassifier
# 학습데이터, 테스트데이터 분리 함수 로드
from sklearn.model_selection import train_test_split

In [3]:
import numpy as np
import pandas as pd

In [4]:
# 붓꽃 데이터 세트를 로딩
iris = load_iris()
type(iris)

sklearn.utils.Bunch

In [10]:
# iris 객체는 딕셔너리 구조로 이루어져 있다.
list(iris.keys())

['data',
 'target',
 'frame',
 'target_names',
 'DESCR',
 'feature_names',
 'filename']

In [11]:
# target 은 답을 의미한다. 0=>setosa, 1=>versicolor, 2=>virginica
iris['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [14]:
# iris의 데이터 추출
iris_data = iris.data

In [16]:
type(iris_data)

numpy.ndarray

In [17]:
# iris.target key: 레이블(답) 데이터 추출
iris_label = iris.target
iris_label

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [21]:
# 품종명 확인
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [22]:
# 추출한 데이터 => 데이터프레임 생성
iris_df = pd.DataFrame(
    data=iris_data
)
iris_df

0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]

In [24]:
# 추출한 데이터 => 데이터프레임 생성
iris_df = pd.DataFrame(
      data=iris_data
    , columns=iris.feature_names # 컬럼명
)
iris_df.head(3)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2

In [27]:
# 레이블(답) 추가
iris_df['label']= iris.target
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     label  
0        0  
1        0  
2        0  
3        0  
4        0  
..     ...  
145      2  
146      2  
147      2  
148      2  
149      2  

[150 rows x 5 columns]

In [35]:
# 전체 데이터 : 150개
# 학습 데이터 : 120개(0.8), 테스트데이터 : 30개(0.2)로 분리하기
# 학습 레이블 : 120개, 테스트 레이블:30 개 분리됨 (위의 데이터와 동일하게.)
# 총 4개의 데이터가 튜플형태로 반환됨 (1.학습데이터, 2.테스트데이터, 3.학습 답, 4.테스트 답)
X_train, X_test, y_train, y_test = train_test_split(
      iris_data  #분리할 데이터
    , iris_label  # 분리할 답(레이블)
    , test_size=0.2  # 테스트데이터의 크기 지정
    , random_state=11 # random_seed 동일, 랜덤값 지정.
)

In [36]:
# 학습데이터, 학습 답
X_train, y_train

(array([[5.1, 3.5, 1.4, 0.2],
        [6.9, 3.2, 5.7, 2.3],
        [7.7, 2.8, 6.7, 2. ],
        [5. , 3.3, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [7.7, 2.6, 6.9, 2.3],
        [7.6, 3. , 6.6, 2.1],
        [6.7, 3. , 5. , 1.7],
        [5.5, 3.5, 1.3, 0.2],
        [6. , 2.7, 5.1, 1.6],
        [5. , 2. , 3.5, 1. ],
        [7.9, 3.8, 6.4, 2. ],
        [4.6, 3.4, 1.4, 0.3],
        [6.9, 3.1, 4.9, 1.5],
        [6.5, 3. , 5.8, 2.2],
        [5.1, 2.5, 3. , 1.1],
        [6.6, 2.9, 4.6, 1.3],
        [5. , 3.2, 1.2, 0.2],
        [7.4, 2.8, 6.1, 1.9],
        [5.1, 3.8, 1.6, 0.2],
        [6.8, 3.2, 5.9, 2.3],
        [6.9, 3.1, 5.1, 2.3],
        [5.9, 3. , 4.2, 1.5],
        [4.9, 2.5, 4.5, 1.7],
        [6.7, 3.1, 4.7, 1.5],
        [4.4, 3.2, 1.3, 0.2],
        [5.4, 3.4, 1.7, 0.2],
        [6.5, 2.8, 4.6, 1.5],
        [5.1, 3.7, 1.5, 0.4],
        [5. , 3.4, 1.6, 0.4],
        [6.1, 2.6, 5.6, 1.4],
        [6.5, 3. , 5.5, 1.8],
        [6.3, 2.5, 5. , 1.9],
        [5

In [37]:
# 테스트 사용될 테스트 데이터, 테스트 답
X_test, y_test

(array([[6.8, 3. , 5.5, 2.1],
        [6.7, 3. , 5.2, 2.3],
        [6.3, 2.8, 5.1, 1.5],
        [6.3, 3.3, 4.7, 1.6],
        [6.4, 2.7, 5.3, 1.9],
        [4.9, 3.1, 1.5, 0.1],
        [6.7, 3.1, 4.4, 1.4],
        [5.7, 4.4, 1.5, 0.4],
        [4.8, 3.1, 1.6, 0.2],
        [6.1, 2.9, 4.7, 1.4],
        [6. , 2.2, 5. , 1.5],
        [6. , 2.2, 4. , 1. ],
        [5.4, 3. , 4.5, 1.5],
        [5.7, 2.5, 5. , 2. ],
        [6.9, 3.1, 5.4, 2.1],
        [4.5, 2.3, 1.3, 0.3],
        [6.3, 2.9, 5.6, 1.8],
        [5.6, 3. , 4.5, 1.5],
        [6.5, 3.2, 5.1, 2. ],
        [5.8, 2.7, 5.1, 1.9],
        [5.6, 2.5, 3.9, 1.1],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.6, 1. , 0.2],
        [6.4, 3.2, 4.5, 1.5],
        [4.8, 3. , 1.4, 0.1],
        [4.8, 3.4, 1.6, 0.2],
        [5.9, 3. , 5.1, 1.8],
        [6.6, 3. , 4.4, 1.4],
        [5.4, 3.9, 1.3, 0.4],
        [6. , 3.4, 4.5, 1.6]]),
 array([2, 2, 2, 1, 2, 0, 1, 0, 0, 1, 2, 1, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0,
        0, 1, 0, 0, 2, 1

In [95]:
# 모델 생성: 학습데이터와 학습답으로 학습한 결과
# 분류로 학습 진행(여기서의 분류 알고리즘은 DTC 를 사용하겠다.)
# DecisionTreeClassifier : 분류 처리 객체만 생성 => 아직 학습 전
dt_clf = DecisionTreeClassifier(random_state=35) #state 값 바뀌어도 상관은 없음
dt_clf

DecisionTreeClassifier(random_state=35)

In [96]:
# 학습데이터, 답을 input하여 DTC 알고리즘으로 학습 수행
dt_clf.fit(X_train, y_train)
# 모델(학습 결과: 식) 생성
# 해당 객체안에 모델이 생성됨.

DecisionTreeClassifier(random_state=35)

In [97]:
# 테스트데이터를 모델에 넣어서 예측 값 출력하기
pred = dt_clf.predict(X_test)
pred

array([2, 2, 1, 1, 2, 0, 1, 0, 0, 1, 1, 1, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0,
       0, 1, 0, 0, 2, 1, 0, 1])

In [98]:
# 0 번째 테스트데이터, 예측값,  정답
X_test[0],             pred[0], y_test[0]

(array([6.8, 3. , 5.5, 2.1]), 2, 2)

In [99]:
pred == y_test

array([ True,  True, False,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [100]:
# np.sum 해야 속도가 빠르다. (브로드캐스팅)
# np.sum(불린조건문) => True 총 개수 반환함.

np.sum(pred==y_test)

28

In [101]:
# 모델의 정확도 계산
np.sum(pred==y_test)/len(pred) *100

93.33333333333333

In [94]:
# 내코드 : 모델의 정확도 계산2
# 아래와 같이 반복문 활용할 수도 있지만, np사용하는 것이 속도 측면에서 빠르고 간결함.
cnt = 0
for i in range(len(pred)):
    if pred[i]==y_test[i]:
        cnt += 1
    else:pass

print("정답율 " + str(round(cnt/len(pred)*100, 2)) + "% 입니다.")

정답율 93.33% 입니다.


In [61]:
# accuracy_score : 정확도 계산 함수 를 이용하면 위와 동일한 기능을 해주므로 편하다.
# pred(예측결과값) == y_test(정답)
from sklearn.metrics import accuracy_score
accuracy_score(y_test, pred)

0.9333333333333333

In [62]:
# 소수점 4자리까지만 출력하기: format 함수 이용 => .4f format 함수 공부하기..
print('예측 정확도 : {0:.4f}'.format(accuracy_score(y_test, pred)))

예측 정확도 : 0.9333


In [102]:
# iris dataset 확인
from sklearn.datasets import load_iris

# iris data 읽기
iris_data = load_iris()

keys=iris_data.keys()
keys

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [104]:
# 컬럼명 추출
iris_data.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [105]:
# 정답에 매칭되는 이름 target name
iris_data.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [107]:
# 데이터의 구조 확인 (행,열)
iris_data.data.shape

(150, 4)

In [109]:
# 정답값 : 0, 1, 2
iris_data.target.shape

(150,)