In [1]:
import numpy as np
import pandas as pd

In [2]:
movies  = pd.read_csv('./data/tmdb/tmdb_5000_movies.csv')

In [3]:
movies.head(2)

budget                                             genres  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   

                                       homepage     id  \
0                   http://www.avatarmovie.com/  19995   
1  http://disney.go.com/disneypictures/pirates/    285   

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   

                                            overview  popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577   
1  Captain Barbossa, long believed to be dead, ha...  139.082615   

                                production_companies  \
0  [{"name": "Ingenious Film Partners", "id": 289...   
1  [{"name": "Walt Disney Pictures", "id": 2}, {"...   

                                production_countries release_date     revenue  \
0  [{"iso_3166_1": "US", "name": "United States o...   2009-12-10  2787965087   
1  [{"iso_3166_1": "US", "name": "United States o...   2007-05-19   961000000   

   runtime                                   spoken_languages    status  \
0    162.0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1    169.0           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   

                                      title  vote_average  vote_count  
0                                    Avatar           7.2       11800  
1  Pirates of the Caribbean: At World's End           6.9        4500

In [4]:
movies['genres'][0]

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [247]:
a = movies['genres'][1]

In [254]:
literal_eval(a)

[{'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 28, 'name': 'Action'}]

In [5]:
type(movies['genres'][0])

str

In [6]:
print(movies.shape)

(4803, 20)


In [7]:
movies.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='object')

In [14]:
movies_df = movies[['id','title','genres','vote_average', 'vote_count','popularity','overview','keywords'
      ]]

In [15]:
movies_df

id                                     title  \
0      19995                                    Avatar   
1        285  Pirates of the Caribbean: At World's End   
2     206647                                   Spectre   
3      49026                     The Dark Knight Rises   
4      49529                               John Carter   
...      ...                                       ...   
4798    9367                               El Mariachi   
4799   72766                                 Newlyweds   
4800  231617                 Signed, Sealed, Delivered   
4801  126186                          Shanghai Calling   
4802   25975                         My Date with Drew   

                                                 genres  vote_average  \
0     [{"id": 28, "name": "Action"}, {"id": 12, "nam...           7.2   
1     [{"id": 12, "name": "Adventure"}, {"id": 14, "...           6.9   
2     [{"id": 28, "name": "Action"}, {"id": 12, "nam...           6.3   
3     [{"id": 28, "name": "Action"}, {"id": 80, "nam...           7.6   
4     [{"id": 28, "name": "Action"}, {"id": 12, "nam...           6.1   
...                                                 ...           ...   
4798  [{"id": 28, "name": "Action"}, {"id": 80, "nam...           6.6   
4799  [{"id": 35, "name": "Comedy"}, {"id": 10749, "...           5.9   
4800  [{"id": 35, "name": "Comedy"}, {"id": 18, "nam...           7.0   
4801                                                 []           5.7   
4802                [{"id": 99, "name": "Documentary"}]           6.3   

      vote_count  popularity  \
0          11800  150.437577   
1           4500  139.082615   
2           4466  107.376788   
3           9106  112.312950   
4           2124   43.926995   
...          ...         ...   
4798         238   14.269792   
4799           5    0.642552   
4800           6    1.444476   
4801           7    0.857008   
4802          16    1.929883   

                                               overview  \
0     In the 22nd century, a paraplegic Marine is di...   
1     Captain Barbossa, long believed to be dead, ha...   
2     A cryptic message from Bond’s past sends him o...   
3     Following the death of District Attorney Harve...   
4     John Carter is a war-weary, former military ca...   
...                                                 ...   
4798  El Mariachi just wants to play his guitar and ...   
4799  A newlywed couple's honeymoon is upended by th...   
4800  "Signed, Sealed, Delivered" introduces a dedic...   
4801  When ambitious New York attorney Sam is sent t...   
4802  Ever since the second grade when he first saw ...   

                                               keywords  
0     [{"id": 1463, "name": "culture clash"}, {"id":...  
1     [{"id": 270, "name": "ocean"}, {"id": 726, "na...  
2     [{"id": 470, "name": "spy"}, {"id": 818, "name...  
3     [{"id": 849, "name": "dc comics"}, {"id": 853,...  
4     [{"id": 818, "name": "based on novel"}, {"id":...  
...                                                 ...  
4798  [{"id": 5616, "name": "united states\u2013mexi...  
4799                                                 []  
4800  [{"id": 248, "name": "date"}, {"id": 699, "nam...  
4801                                                 []  
4802  [{"id": 1523, "name": "obsession"}, {"id": 224...  

[4803 rows x 8 columns]

In [25]:
movies_df[['genres','keywords']]

genres  \
0     [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1     [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2     [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3     [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4     [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
...                                                 ...   
4798  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4799  [{"id": 35, "name": "Comedy"}, {"id": 10749, "...   
4800  [{"id": 35, "name": "Comedy"}, {"id": 18, "nam...   
4801                                                 []   
4802                [{"id": 99, "name": "Documentary"}]   

                                               keywords  
0     [{"id": 1463, "name": "culture clash"}, {"id":...  
1     [{"id": 270, "name": "ocean"}, {"id": 726, "na...  
2     [{"id": 470, "name": "spy"}, {"id": 818, "name...  
3     [{"id": 849, "name": "dc comics"}, {"id": 853,...  
4     [{"id": 818, "name": "based on novel"}, {"id":...  
...                                                 ...  
4798  [{"id": 5616, "name": "united states\u2013mexi...  
4799                                                 []  
4800  [{"id": 248, "name": "date"}, {"id": 699, "nam...  
4801                                                 []  
4802  [{"id": 1523, "name": "obsession"}, {"id": 224...  

[4803 rows x 2 columns]

In [26]:
movies_df[['genres','keywords']].info()
# object 로 되어있다(str) => dictionary 로 변환 필요

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   genres    4803 non-null   object
 1   keywords  4803 non-null   object
dtypes: object(2)
memory usage: 75.2+ KB


In [27]:
from ast import literal_eval  # 문자열을 문자열이 의미하는 객체로 변환

In [30]:
movies_df['genres'] = movies_df['genres'].apply(literal_eval)

C:\Users\TJ\anaconda3\envs\ml01-02\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [33]:
# 위 문자열을 리스트로 바뀜
movies_df['genres'].values

array([list([{'id': 28, 'name': 'Action'}, {'id': 12, 'name': 'Adventure'}, {'id': 14, 'name': 'Fantasy'}, {'id': 878, 'name': 'Science Fiction'}]),
       list([{'id': 12, 'name': 'Adventure'}, {'id': 14, 'name': 'Fantasy'}, {'id': 28, 'name': 'Action'}]),
       list([{'id': 28, 'name': 'Action'}, {'id': 12, 'name': 'Adventure'}, {'id': 80, 'name': 'Crime'}]),
       ...,
       list([{'id': 35, 'name': 'Comedy'}, {'id': 18, 'name': 'Drama'}, {'id': 10749, 'name': 'Romance'}, {'id': 10770, 'name': 'TV Movie'}]),
       list([]), list([{'id': 99, 'name': 'Documentary'}])], dtype=object)

In [41]:
for genre in genres:
    movies_df['genres'].values[]

movies_df['genres'].values[0][i]

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [42]:
movies_df['keywords'] = movies_df['keywords'].apply(literal_eval)

C:\Users\TJ\anaconda3\envs\ml01-02\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [51]:
movies_df['keywords'].values

array([list([{'id': 1463, 'name': 'culture clash'}, {'id': 2964, 'name': 'future'}, {'id': 3386, 'name': 'space war'}, {'id': 3388, 'name': 'space colony'}, {'id': 3679, 'name': 'society'}, {'id': 3801, 'name': 'space travel'}, {'id': 9685, 'name': 'futuristic'}, {'id': 9840, 'name': 'romance'}, {'id': 9882, 'name': 'space'}, {'id': 9951, 'name': 'alien'}, {'id': 10148, 'name': 'tribe'}, {'id': 10158, 'name': 'alien planet'}, {'id': 10987, 'name': 'cgi'}, {'id': 11399, 'name': 'marine'}, {'id': 13065, 'name': 'soldier'}, {'id': 14643, 'name': 'battle'}, {'id': 14720, 'name': 'love affair'}, {'id': 165431, 'name': 'anti war'}, {'id': 193554, 'name': 'power relations'}, {'id': 206690, 'name': 'mind and soul'}, {'id': 209714, 'name': '3d'}]),
       list([{'id': 270, 'name': 'ocean'}, {'id': 726, 'name': 'drug abuse'}, {'id': 911, 'name': 'exotic island'}, {'id': 1319, 'name': 'east india trading company'}, {'id': 2038, 'name': "love of one's life"}, {'id': 2052, 'name': 'traitor'}, {'id'

In [52]:
# ndarray니까 반복문 없이 apply 로 전체 적용가능
movies_df['genres'][0]

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [ ]:
'''
[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]
 '''
# 위의 구조에서 장르('name')만, 리스트로 뽑아내서 장르에 다시 저장

In [55]:
movies_df['genres'] = movies_df['genres'].apply(lambda x :[y['name'] for y in x])

C:\Users\TJ\anaconda3\envs\ml01-02\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [57]:
movies_df['keywords'][0]

[{'id': 1463, 'name': 'culture clash'},
 {'id': 2964, 'name': 'future'},
 {'id': 3386, 'name': 'space war'},
 {'id': 3388, 'name': 'space colony'},
 {'id': 3679, 'name': 'society'},
 {'id': 3801, 'name': 'space travel'},
 {'id': 9685, 'name': 'futuristic'},
 {'id': 9840, 'name': 'romance'},
 {'id': 9882, 'name': 'space'},
 {'id': 9951, 'name': 'alien'},
 {'id': 10148, 'name': 'tribe'},
 {'id': 10158, 'name': 'alien planet'},
 {'id': 10987, 'name': 'cgi'},
 {'id': 11399, 'name': 'marine'},
 {'id': 13065, 'name': 'soldier'},
 {'id': 14643, 'name': 'battle'},
 {'id': 14720, 'name': 'love affair'},
 {'id': 165431, 'name': 'anti war'},
 {'id': 193554, 'name': 'power relations'},
 {'id': 206690, 'name': 'mind and soul'},
 {'id': 209714, 'name': '3d'}]

In [58]:
movies_df['keywords'] = movies_df['keywords'].apply(lambda x :[y['name'] for y in x])

C:\Users\TJ\anaconda3\envs\ml01-02\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [61]:
movies_df['genres'][:3]

0    [Action, Adventure, Fantasy, Science Fiction]
1                     [Adventure, Fantasy, Action]
2                       [Action, Adventure, Crime]
Name: genres, dtype: object

In [63]:
movies_df['keywords'][0]

['culture clash',
 'future',
 'space war',
 'space colony',
 'society',
 'space travel',
 'futuristic',
 'romance',
 'space',
 'alien',
 'tribe',
 'alien planet',
 'cgi',
 'marine',
 'soldier',
 'battle',
 'love affair',
 'anti war',
 'power relations',
 'mind and soul',
 '3d']

In [69]:
movies_df[['genres','keywords']][:1]

genres  \
0  [Action, Adventure, Fantasy, Science Fiction]   

                                            keywords  
0  [culture clash, future, space war, space colon...

In [75]:
# 1. 장르 : 리스트 => 문자열
movies_df['genres_literal'] = movies_df['genres'].apply(lambda x: (' ').join(x))

C:\Users\TJ\anaconda3\envs\ml01-02\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.


In [85]:
movies_df['genres_literal']

0       Action Adventure Fantasy Science Fiction
1                       Adventure Fantasy Action
2                         Action Adventure Crime
3                    Action Crime Drama Thriller
4               Action Adventure Science Fiction
                          ...                   
4798                       Action Crime Thriller
4799                              Comedy Romance
4800               Comedy Drama Romance TV Movie
4801                                            
4802                                 Documentary
Name: genres_literal, Length: 4803, dtype: object

In [80]:
# 2. 벡터화
from sklearn.feature_extraction.text import CountVectorizer
count_vect = CountVectorizer(min_df=0, ngram_range=(1,2))

In [81]:
# 3. 유사도
genre_mat = count_vect.fit_transform(movies_df['genres_literal'])

In [110]:
genre_mat.shape

(4803, 276)

In [258]:
len(count_vect.get_feature_names())

276

In [260]:
count_vect.get_feature_names()[:5]

['action',
 'action adventure',
 'action animation',
 'action comedy',
 'action crime']

In [263]:
genre_mat

<4803x276 sparse matrix of type '<class 'numpy.int64'>'
	with 20631 stored elements in Compressed Sparse Row format>

- 4803개의 영화가 276개의 장르로 Counting 된 결과

In [114]:
# 4. 장르 유사도 높은 영화 추출(코사인유사도)
from sklearn.metrics.pairwise import cosine_similarity

genre_sim = cosine_similarity(genre_mat, genre_mat)

In [115]:
genre_sim.shape

(4803, 4803)

In [116]:
genre_sim[:1][0]

array([1.        , 0.59628479, 0.4472136 , ..., 0.        , 0.        ,
       0.        ])

In [129]:
genre_sim_sorted_ind = genre_sim.argsort()[:,::-1]
genre_sim_sorted_ind[:1]

array([[   0, 3494,  813, ..., 3038, 3037, 2401]], dtype=int64)

In [133]:
genre_sim_sorted_ind[:1][0][:10]

array([   0, 3494,  813,  870,   46,   14, 1296, 1652,  419,  420],
      dtype=int64)

In [136]:
# 0번 영화인 'Avater' 와 장르적으로 가장 유사한 영화 확인하기
movies_df.iloc[3494,:]['title']

'Beastmaster 2: Through the Portal of Time'

In [170]:
# 상위 5개 출력
movies_df.iloc[genre_sim_sorted_ind[0][:5],:]['title']

0                                          Avatar
3494    Beastmaster 2: Through the Portal of Time
813                                      Superman
870                                   Superman II
46                     X-Men: Days of Future Past
Name: title, dtype: object

In [171]:
movies_df.iloc[genre_sim_sorted_ind[2][:5],:]['title']

2          Spectre
1740    Kick-Ass 2
1542         Speed
1082     16 Blocks
873          Shaft
Name: title, dtype: object

In [237]:
# 5. 평점이 높은 영화 추출 => 함수 생성
# parameter : df : 전체 데이터 프레임, sorted_ind: 유사도 인덱스, 영화제목, 추천 개수
def find_sim_movie(df, sorted_ind, title_name, top_n=10):
    # title_name 값인 DataFrame 추출
    title_movie = df[df['title']==title_name]
    # title_movie의 인덱스를 이용해서 유사한 애들 top_n만큼 만들기
    title_index = title_movie.index.values
    similar_indexes = sorted_ind[title_index, :(top_n)]
    # 유사도 인덱스 1차원으로 변환(원래 2차원이어서)
    similar_indexes = similar_indexes.reshape(-1)
    
    # top_n개의 영화 정보가 들어가 있는 영화정보 반환
    return df.iloc[similar_indexes]

In [173]:
title_movie = movies_df[movies_df['title']=='Avatar']

In [174]:
title_movie

id   title                                         genres  vote_average  \
0  19995  Avatar  [Action, Adventure, Fantasy, Science Fiction]           7.2   

   vote_count  popularity                                           overview  \
0       11800  150.437577  In the 22nd century, a paraplegic Marine is di...   

                                            keywords  \
0  [culture clash, future, space war, space colon...   

                             genres_literal  
0  Action Adventure Fantasy Science Fiction

In [185]:
title_movie.index.values

array([0], dtype=int64)

In [187]:
similar_indexes = genre_sim_sorted_ind[title_movie.index.values, :10]

In [189]:
similar_indexes

array([[   0, 3494,  813,  870,   46,   14, 1296, 1652,  419,  420]],
      dtype=int64)

In [190]:
similar_indexes.reshape(-1)

array([   0, 3494,  813,  870,   46,   14, 1296, 1652,  419,  420],
      dtype=int64)

In [207]:
similar_movies= find_sim_movie(movies_df, genre_sim_sorted_ind, 'Avatar')
similar_movies

id                                      title  \
0      19995                                     Avatar   
3494   27549  Beastmaster 2: Through the Portal of Time   
813     1924                                   Superman   
870     8536                                Superman II   
46    127585                 X-Men: Days of Future Past   
14     49521                               Man of Steel   
1296    9531                               Superman III   
1652   14164                       Dragonball Evolution   
419     8247                                     Jumper   
420    11253                Hellboy II: The Golden Army   

                                                 genres  vote_average  \
0         [Action, Adventure, Fantasy, Science Fiction]           7.2   
3494      [Action, Adventure, Fantasy, Science Fiction]           4.6   
813       [Action, Adventure, Fantasy, Science Fiction]           6.9   
870       [Action, Adventure, Fantasy, Science Fiction]           6.5   
46        [Action, Adventure, Fantasy, Science Fiction]           7.5   
14        [Action, Adventure, Fantasy, Science Fiction]           6.5   
1296  [Comedy, Action, Adventure, Fantasy, Science F...           5.3   
1652  [Action, Adventure, Fantasy, Science Fiction, ...           2.9   
419               [Adventure, Fantasy, Science Fiction]           5.9   
420               [Adventure, Fantasy, Science Fiction]           6.5   

      vote_count  popularity  \
0          11800  150.437577   
3494          17    1.478505   
813         1022   48.507081   
870          629   30.515175   
46          6032  118.078691   
14          6359   99.398009   
1296         490   22.164202   
1652         462   21.677732   
419         1799   21.218000   
420         1527   58.579760   

                                               overview  \
0     In the 22nd century, a paraplegic Marine is di...   
3494  Mark Singer returns as Dar, the warrior who ca...   
813   Mild-mannered Clark Kent works as a reporter a...   
870   Three escaped criminals from the planet Krypto...   
46    The ultimate X-Men ensemble fights a war for t...   
14    A young boy learns that he has extraordinary p...   
1296  Aiming to defeat the Man of Steel, wealthy exe...   
1652  The young warrior Son Goku sets out on a quest...   
419   David Rice is a man who knows no boundaries, a...   
420   In this continuation to the adventure of the d...   

                                               keywords  \
0     [culture clash, future, space war, space colon...   
3494  [based on novel, time travel, sequel, psychotr...   
813   [saving the world, journalist, dc comics, crim...   
870   [saving the world, dc comics, sequel, superher...   
46    [1970s, mutant, time travel, marvel comic, bas...   
14    [saving the world, dc comics, superhero, based...   
1296  [saving the world, dc comics, super computer, ...   
1652  [karate, superhero, revenge, dragon, duringcre...   
419   [adolescence, based on novel, loss of child, f...   
420   [auction, northern ireland, resignation, super...   

                                         genres_literal  
0              Action Adventure Fantasy Science Fiction  
3494           Action Adventure Fantasy Science Fiction  
813            Action Adventure Fantasy Science Fiction  
870            Action Adventure Fantasy Science Fiction  
46             Action Adventure Fantasy Science Fiction  
14             Action Adventure Fantasy Science Fiction  
1296    Comedy Action Adventure Fantasy Science Fiction  
1652  Action Adventure Fantasy Science Fiction Thriller  
419                   Adventure Fantasy Science Fiction  
420                   Adventure Fantasy Science Fiction

In [208]:
# 유사한 영화 데이터에서, 다시 평점으로 sort
similar_movies[['title','vote_average','vote_count']].sort_values(by='vote_average', ascending=False)

title  vote_average  vote_count
46                   X-Men: Days of Future Past           7.5        6032
0                                        Avatar           7.2       11800
813                                    Superman           6.9        1022
870                                 Superman II           6.5         629
14                                 Man of Steel           6.5        6359
420                 Hellboy II: The Golden Army           6.5        1527
419                                      Jumper           5.9        1799
1296                               Superman III           5.3         490
3494  Beastmaster 2: Through the Portal of Time           4.6          17
1652                       Dragonball Evolution           2.9         462

In [209]:
# 평점으로 전체 데이터 sort
movies_df[['title','vote_average','vote_count']].sort_values(by='vote_average', ascending=False)[:10]

title  vote_average  vote_count
3519          Stiff Upper Lips          10.0           1
4247     Me You and Five Bucks          10.0           2
4045     Dancer, Texas Pop. 81          10.0           1
4662            Little Big Top          10.0           1
3992                 Sardaarji           9.5           2
2386            One Man's Hero           9.3           2
2970        There Goes My Baby           8.5           2
1881  The Shawshank Redemption           8.5        8205
2796     The Prisoner of Zenda           8.4          11
3337             The Godfather           8.4        5893

- 평점 순으로 sort 했지만, vote_count가 너무 낮다. 
- vote_count 에 가중치를 부여해서 보다 신뢰성 있는 데이터 프레임을 만들자

In [227]:
# 전체 영화 데이터에서 평점 개수에 평균 평점에 가중치 처리하기
'''
가중평점(Weighted Rating) = (v/(v+m))*R + (m/(v+m))*C
'''

# 전체 영화에 대한 평균평점, C 구하기 
C = movies_df['vote_average'].mean()
# 최소 투표횟수: m 지정(전체 투표 횟수에서 상위 60% 의 위치값을 가져온다.)
percentile = 0.6
m = movies_df['vote_count'].quantile(percentile)

print('60% 위치값 : ', round(m))
print('C : 전체 영화 평균평점 : ', round(C))

60% 위치값 :  370
C : 전체 영화 평균평점 :  6


In [224]:
# 전체 투표 횟수에서 상위 60% 의 위치값을 가져온다.
movies_df['vote_count'].quantile(0.6)

370.1999999999998

In [219]:
movies_df['vote_count']

0       11800
1        4500
2        4466
3        9106
4        2124
        ...  
4798      238
4799        5
4800        6
4801        7
4802       16
Name: vote_count, Length: 4803, dtype: int64

In [230]:
# 함수로 만들기
def weighted_vote_average(record):
    v = record['vote_count']
    R = record['vote_average']
    
    return ( (v/(v+m))*R) + ( (m/(m+v))*C)

In [231]:
movies_df['weighted_vote'] = movies_df.apply(weighted_vote_average, axis=1)

C:\Users\TJ\anaconda3\envs\ml01-02\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [234]:
movies_df[['title','vote_average','weighted_vote','vote_count']].sort_values(by='weighted_vote', ascending=False)[:10]

title  vote_average  weighted_vote  vote_count
1881  The Shawshank Redemption           8.5       8.396052        8205
3337             The Godfather           8.4       8.263591        5893
662                 Fight Club           8.3       8.216455        9413
3232              Pulp Fiction           8.3       8.207102        8428
65             The Dark Knight           8.2       8.136930       12002
1818          Schindler's List           8.3       8.126069        4329
3865                  Whiplash           8.3       8.123248        4254
809               Forrest Gump           8.2       8.105954        7927
2294             Spirited Away           8.3       8.105867        3840
2731    The Godfather: Part II           8.3       8.079586        3338

In [236]:
# 함수 변경

def find_sim_movie_02(df, sorted_ind, title_name, top_n=10):
    # title_name 값인 DataFrame 추출
    title_movie = df[df['title']==title_name]
    # title_movie의 인덱스를 이용해서 유사한 애들 top_n만큼 만들기
    title_index = title_movie.index.values
    similar_indexes = sorted_ind[title_index, :(top_n*2)]
    # 유사도 인덱스 1차원으로 변환(원래 2차원이어서)
    similar_indexes = similar_indexes.reshape(-1)
    
    # 자기 자신의 idx는 제외
    similar_indexes = similar_indexes[similar_indexes != title_index]
 
    
    # top_n개의 영화 정보가 들어가 있는 영화정보
    return df.iloc[similar_indexes].sort_values(by='weighted_vote', ascending =False)[:top_n]

In [246]:
# 이전에 만든 함수 적용
similar_movies= find_sim_movie(movies_df, genre_sim_sorted_ind, 'The Godfather')
similar_movies[['title', 'vote_average','vote_count','weighted_vote']][:5]

title  vote_average  \
2731                          The Godfather: Part II           8.3   
1243                                    Mean Streets           7.2   
3636                                   Light Sleeper           5.7   
1946  The Bad Lieutenant: Port of Call - New Orleans           6.0   
2640         Things to Do in Denver When You're Dead           6.7   

      vote_count  weighted_vote  
2731        3338       8.079586  
1243         345       6.626569  
3636          15       6.076900  
1946         326       6.049012  
2640          85       6.205672

In [245]:
# 평점 가중치 처리되어 있고, 본인을 제외하는 function 적용
similar_movies= find_sim_movie_02(movies_df, genre_sim_sorted_ind, 'The Godfather')
similar_movies[['title', 'vote_average','vote_count','weighted_vote']][:5]

title  vote_average  vote_count  weighted_vote
2731       The Godfather: Part II           8.3        3338       8.079586
1847                   GoodFellas           8.2        3128       7.976937
3866                  City of God           8.1        1814       7.759693
1663  Once Upon a Time in America           8.2        1069       7.657811
883           Catch Me If You Can           7.7        3795       7.557097